<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>aswf</AssemblyName>
    <RootNamespace>AgenticSoftwareWorkflow.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
    <PackageReference Include="LanguageExt.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AgenticSoftwareWorkflow.Conductor/AgenticSoftwareWorkflow.Conductor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AgenticSoftwareWorkflow.Conductor.Test" />
  </ItemGroup>

</Project>
