<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AgenticSoftwareWorkflow.Conductor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AgenticSoftwareWorkflow.Conductor.Test" />
  </ItemGroup>

</Project>
